# 对象的布尔值
print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool(None))
print(bool(''))
print(bool([]))
print(bool(list()))
print(bool(()))
print(bool(( )))
print(bool(tuple()))
print(bool({}))
print(bool(dict()))
print(bool(set()))
print("----以上对象为false,其余为true------")
print(bool(15))
print(bool(True))